//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cybersource.FlexMicroformSdk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReasonCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReasonCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cybersource.FlexMicroformSdk.ReasonCode", typeof(ReasonCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer system error..
        /// </summary>
        public static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful transaction..
        /// </summary>
        public static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is missing one or more required fields. Possible action: see the reply fields missingField_0...N for which fields are missing. Resend the request with the complete information. .
        /// </summary>
        public static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields in the request contain invalid data..
        /// </summary>
        public static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General system failure..
        /// </summary>
        public static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was received but there was a server timeout. This error does not include timeouts between the client and the server. To avoid duplicating the transaction, do not resend the request until you have reviewed the transaction status in the Business Center or using Transaction Search REST API request. .
        /// </summary>
        public static string _151 {
            get {
                return ResourceManager.GetString("151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was received, but a service did not finish running in time. To avoid duplicating the transaction, do not resend the request until you have reviewed the transaction status in the Business Center or using Transaction Search REST API request. .
        /// </summary>
        public static string _152 {
            get {
                return ResourceManager.GetString("152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization request was approved by the issuing bank but declined by Cybersource because it did not pass the Address Verification System (AVS) check. You can capture the authorization but consider reviewing the order for possible fraud..
        /// </summary>
        public static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issuing bank has questions about the request. You do not receive an authorization code programmatically, but you might receive one verbally by calling the processor..
        /// </summary>
        public static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General decline of the card. No other information was provided by the issuing bank. Request a different card or other form of payment..
        /// </summary>
        public static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was received, but there was a timeout at the payment processor. To avoid duplicating the transaction, do not resend the request until you have reviewed the transaction status in the Business Center or using Transaction Search REST API request..
        /// </summary>
        public static string _250 {
            get {
                return ResourceManager.GetString("250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer is enrolled in Payer Authentication. Authenticate the cardholder before continuing with the transaction..
        /// </summary>
        public static string _475 {
            get {
                return ResourceManager.GetString("475", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer cannot be authenticated..
        /// </summary>
        public static string _476 {
            get {
                return ResourceManager.GetString("476", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is marked for review by Decision Manager/FME..
        /// </summary>
        public static string _480 {
            get {
                return ResourceManager.GetString("480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is rejected by Decision Manager/FME..
        /// </summary>
        public static string _481 {
            get {
                return ResourceManager.GetString("481", resourceCulture);
            }
        }
    }
}
