name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_TIME_APIKEY }}
          GH_TOKEN: ${{ secrets.GHP_TOKEN }}
          COMMIT_BY_ME: "True"
          SHOW_PROJECTS: "False"
          SHOW_DAYS_OF_WEEK: "True"
    
