# Workflow for building and deploying a Nuxt site to GitHub Pages
name: Deploy Nuxt to GitHub Pages

on:
  # Runs on pushes targeting the default branch when nuxt folder changes
  push:
    branches: ["main"]
    paths:
      - 'nuxt/**'
      - '.github/workflows/nuxt-gh-pages.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages-nuxt"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './nuxt/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./nuxt
        run: npm ci
      
      - name: Generate static files
        working-directory: ./nuxt
        run: npm run generate
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './nuxt/.output/public'

  # Deployment job
  deploy:
    environment:
      name: github-pages-nuxt
      url: ${{ steps.deployment.outputs.page_url }}nuxt/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4